BEGIN TRANSACTION;
CREATE TABLE 'clan_invite_level_group' ('level_group_id' INTEGER NOT NULL, 'team_level_from' INTEGER NOT NULL, 'team_level_to' INTEGER NOT NULL, PRIMARY KEY('level_group_id'));
INSERT INTO "clan_invite_level_group" VALUES(1,1,14);
INSERT INTO "clan_invite_level_group" VALUES(2,15,20);
INSERT INTO "clan_invite_level_group" VALUES(3,21,25);
INSERT INTO "clan_invite_level_group" VALUES(4,26,30);
INSERT INTO "clan_invite_level_group" VALUES(5,31,35);
INSERT INTO "clan_invite_level_group" VALUES(6,36,40);
INSERT INTO "clan_invite_level_group" VALUES(7,41,45);
INSERT INTO "clan_invite_level_group" VALUES(8,46,50);
INSERT INTO "clan_invite_level_group" VALUES(9,51,55);
INSERT INTO "clan_invite_level_group" VALUES(10,56,60);
INSERT INTO "clan_invite_level_group" VALUES(11,61,65);
INSERT INTO "clan_invite_level_group" VALUES(12,66,70);
INSERT INTO "clan_invite_level_group" VALUES(13,71,75);
INSERT INTO "clan_invite_level_group" VALUES(14,76,80);
INSERT INTO "clan_invite_level_group" VALUES(15,81,-1);
COMMIT;