BEGIN TRANSACTION;
CREATE TABLE 'equipment_donation' ('team_level' INTEGER NOT NULL, 'donation_num_once' INTEGER NOT NULL, 'donation_num_daily' INTEGER NOT NULL, 'request_num_once' INTEGER NOT NULL, PRIMARY KEY('team_level'));
INSERT INTO "equipment_donation" VALUES(10,2,10,10);
INSERT INTO "equipment_donation" VALUES(20,2,10,10);
INSERT INTO "equipment_donation" VALUES(30,2,10,10);
INSERT INTO "equipment_donation" VALUES(40,2,10,10);
INSERT INTO "equipment_donation" VALUES(50,2,10,10);
INSERT INTO "equipment_donation" VALUES(60,2,10,10);
INSERT INTO "equipment_donation" VALUES(70,2,10,10);
INSERT INTO "equipment_donation" VALUES(80,2,10,10);
INSERT INTO "equipment_donation" VALUES(999,2,10,10);
COMMIT;