BEGIN TRANSACTION;
CREATE TABLE 'hatsune_description' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'description' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO "hatsune_description" VALUES(1,10001,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーは、イベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(2,10001,1,'イベントクエストを進めるとボスが登場します。\nボスには、ボスチケットを使うことで挑むことができます。\nボス撃破で、討伐証を大量にゲットできるので、思い切って挑戦しましょう。');
INSERT INTO "hatsune_description" VALUES(3,10001,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(4,10002,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(5,10002,1,'イベントクエストを進めるとボスが登場します。\nボスには、ボスチケットを使うことで挑むことができます。\nボス撃破で討伐証を大量にゲットできるので思い切って挑戦しましょう。');
INSERT INTO "hatsune_description" VALUES(6,10002,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(7,10003,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(8,10003,1,'イベントクエストを進めるとボスが登場します。\nボスには、ボスチケットを使うことで挑むことができます。\nボス撃破で討伐証を大量にゲットできるので思い切って挑戦しましょう。');
INSERT INTO "hatsune_description" VALUES(9,10003,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(10,10004,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(11,10004,1,'イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。');
INSERT INTO "hatsune_description" VALUES(12,10004,1,'強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。');
INSERT INTO "hatsune_description" VALUES(13,10004,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(14,10005,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(15,10005,1,'イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。');
INSERT INTO "hatsune_description" VALUES(16,10005,1,'強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。');
INSERT INTO "hatsune_description" VALUES(17,10005,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(18,10006,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(19,10006,1,'強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。');
INSERT INTO "hatsune_description" VALUES(20,10006,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(21,10007,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(22,10007,1,'イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。');
INSERT INTO "hatsune_description" VALUES(23,10007,1,'強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。');
INSERT INTO "hatsune_description" VALUES(24,10007,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(25,10008,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(26,10008,1,'強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。');
INSERT INTO "hatsune_description" VALUES(27,10008,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(28,10009,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(29,10009,1,'イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。');
INSERT INTO "hatsune_description" VALUES(30,10009,1,'強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。');
INSERT INTO "hatsune_description" VALUES(31,10009,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(32,10010,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(33,10010,1,'イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。');
INSERT INTO "hatsune_description" VALUES(34,10010,1,'強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。');
INSERT INTO "hatsune_description" VALUES(35,10010,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(36,10010,3,'スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。');
INSERT INTO "hatsune_description" VALUES(37,10011,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(38,10011,1,'イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。');
INSERT INTO "hatsune_description" VALUES(39,10011,1,'強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。');
INSERT INTO "hatsune_description" VALUES(40,10011,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(41,10011,3,'スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。');
INSERT INTO "hatsune_description" VALUES(42,10012,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(43,10012,1,'強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。');
INSERT INTO "hatsune_description" VALUES(44,10012,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(45,10012,3,'スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。');
INSERT INTO "hatsune_description" VALUES(46,10013,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(47,10013,1,'イベント限定のミッションを達成すると解放できる\nキャラが登場します。イベントの期間内に\nミッションクリアを目指しましょう。');
INSERT INTO "hatsune_description" VALUES(48,10013,1,'強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。');
INSERT INTO "hatsune_description" VALUES(49,10013,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(50,10013,3,'スペシャルバトルはバトルモードが３段階変化するバトルです。\nより豪華な報酬やミッション報酬をゲットしましょう。期間中１体しか討伐できないので編成を工夫して挑戦しましょう。');
INSERT INTO "hatsune_description" VALUES(51,10014,1,'イベントでは、特別なストーリーを楽しめます。\nイベントストーリーはイベントクエストを進めると解放されていきます。');
INSERT INTO "hatsune_description" VALUES(52,10014,1,'イベントクエストを進めるとボスが登場します。\nボスには、ボスチケットを使うことで挑むことができます。\nボス撃破で討伐証を大量にゲットできるので思い切って挑戦しましょう。');
INSERT INTO "hatsune_description" VALUES(53,10014,1,'強力なボス、VERY HARDが登場します。\nVERY HARDボスは１日に１体討伐が可能です。\n準備をしっかりして、気を引き締めて挑みましょう。');
INSERT INTO "hatsune_description" VALUES(54,10014,1,'討伐証交換は、報酬ゲットのチャンスです。\n報酬の中には、イベントに登場するキャラのメモリーピースもあります。\nたくさん集めてキャラを仲間にしましょう。');
INSERT INTO "hatsune_description" VALUES(1000802001,10008,2,'働き口を求め、渓谷の洞窟へと向かうアンナ。\n古文書目当てに、仕入れ先へと向かうナナカ。\n村人の願いを聞き入れ、村へと向かうルカ。\n3人は各々の目的地へと出発するのだった。');
INSERT INTO "hatsune_description" VALUES(1000802002,10008,2,'村で悪党を鮮やかに成敗したルカ。\n報復に怯える村人との会話の中で、\n彼女は渓谷一帯で暗躍する巨悪の存在に勘付く。\n一方、渓谷の洞窟へと向かったアンナは・・・。');
INSERT INTO "hatsune_description" VALUES(1000802003,10008,2,'渓谷の洞窟で働き始めたアンナたちだったが、\nそこは事前の話とは違い、無法者がはびこり、\n過酷な労働が支配する劣悪な環境だった。\nそのころ、仕入先へと向かったナナカは・・・。');
INSERT INTO "hatsune_description" VALUES(1000802004,10008,2,'とある貴族に古文書を独占されてしまい、\n仕入の目的を果たすことができなかったナナカ。\n帰る道すがら悪党に襲われた彼女は、\nルカと合流するべく村への道を急ぐのだった・・・。');
INSERT INTO "hatsune_description" VALUES(1000802005,10008,2,'渓谷の洞窟が悪党の本拠地であることを知り、\nアンナたちとの合流を目指すルカとナナカ。\n辛くも脱出したアンナたちを救出し、\n一同はひとまず洞窟から退くことにする。');
INSERT INTO "hatsune_description" VALUES(1001002001,10010,2,'願いを奉じ、浄化する神殿。ここでは、\n成就しなかった「具現化した願い」が人を襲うので\nユイ達に警備の依頼がきていた。報酬からお年玉を\n渡すため警備に参加する。');
INSERT INTO "hatsune_description" VALUES(1001002002,10010,2,'参拝客で慌ただしくなるも、困っているみんなで\n助け合ってもらいつつ、仕事をこなしていく一同。\nそこに、親を探す「具現化した願い」が現れるが、\n親として優しく接するヒヨリ達に浄化された。');
INSERT INTO "hatsune_description" VALUES(1001002003,10010,2,'仕事に慣れてきた一同だが、そこに彼女とキスを\nする方法を知りたい「具現化した願い」が現れる。\nだが、体勢を崩したユイを庇い、キスする寸前の\n主人公達の姿を見て浄化した。');
INSERT INTO "hatsune_description" VALUES(1001002004,10010,2,'夜が近づき、参拝客も増えて忙しさが増す一同。\nそこに「具現化した願い」が現れる。\n元気づけて欲しいと嘆き彷徨うが、\nレイの「必死」な応援で浄化するのであった。');
INSERT INTO "hatsune_description" VALUES(1001002005,10010,2,'多くの願いを浄化し、一度休憩を入れる一同。\nその時、願いが最も濃くなるという\n年末までの数時間が訪れ、願いが次々と具現化。\n暴走した願いは、黒い霧となって神殿を覆った。');
COMMIT;