BEGIN TRANSACTION;
CREATE TABLE 'notif_data' ('unit_id' INTEGER NOT NULL, 'notif_type' INTEGER NOT NULL, 'comment' TEXT NOT NULL, PRIMARY KEY('unit_id','notif_type'));
INSERT INTO "notif_data" VALUES(100101,1,'stamina is back at full! I''m bursting with energy, too! Once you''re ready, let''s get out there and do some quests!');
INSERT INTO "notif_data" VALUES(100101,2,'You have full skip tickets at the guildhouse! Let''s go bop those baddies lickety-split!');
INSERT INTO "notif_data" VALUES(100101,3,'Mr. Knight! Guildhouse stamina is at full! Being in shape is a key part of helping those in need!');
INSERT INTO "notif_data" VALUES(100101,4,'The guildhouse is fully packed with EXP potions! We''ve got to drink lots and lots of these so we can get even stronger!');
INSERT INTO "notif_data" VALUES(100101,5,'The guildhouse is bursting with Mana! It must be tough choosing how to spend it! Or have you already decided, Mr. Knight?');
INSERT INTO "notif_data" VALUES(100101,6,'Yahoo! All items at the guildhouse are full! Oh, sorry... are you busy with something right now, Mr. Knight?');
INSERT INTO "notif_data" VALUES(100201,1,'Mr. Knight, your stamina is back to full again. If you''re going out into the field, I sure hope you take me along.');
INSERT INTO "notif_data" VALUES(100201,2,'The skip tickets are all full at the guildhouse. Does this mean we won''t have to fight as much?');
INSERT INTO "notif_data" VALUES(100201,3,'You have full stamina at the guildhouse. Um, Mr. Knight? What do you say we step out somewhere for a bit?');
INSERT INTO "notif_data" VALUES(100201,4,'You have full EXP potions back at the guildhouse. Hopefully they can help me improve my spellcasting a little...');
INSERT INTO "notif_data" VALUES(100201,5,'The Mana back at the guildhouse is full again. I wonder if I can become a bit stronger, too...');
INSERT INTO "notif_data" VALUES(100201,6,'Mr. Knight, you have full items at the guildhouse. How about we go collect them together?');
INSERT INTO "notif_data" VALUES(100301,1,'I see that you have full stamina again. The surest way to grow stronger is to gain experience in actual combat. So let''s get out there and fight!');
INSERT INTO "notif_data" VALUES(100301,2,'Your skip tickets are full at the guildhouse. Being able to dispatch foes so quickly is proof that our skills have improved.');
INSERT INTO "notif_data" VALUES(100301,3,'I see you have full stamina at the guildhouse. If you''re feeling extra energetic, I''d appreciate it if you helped me train.');
INSERT INTO "notif_data" VALUES(100301,4,'You have full EXP potions at the guildhouse. Diligent study is the quickest way to the next victory.');
INSERT INTO "notif_data" VALUES(100301,5,'The guildhouse has full Mana again. With that, I can refine my swordplay even further. I feel as though my skills are going to reach new heights!');
INSERT INTO "notif_data" VALUES(100301,6,'You have items waiting for you at the guildhouse. You need to collect them quickly. Understood?');
INSERT INTO "notif_data" VALUES(100401,1,'Hey mister, your stamina is totally full! Now we can go have some fun!');
INSERT INTO "notif_data" VALUES(100401,2,'You''ve got full skip tickets at the guildhouse, mister! Looks like you and me oughtta go on a big expedition!');
INSERT INTO "notif_data" VALUES(100401,3,'Your stamina is full back at the guildhouse! C''mon, mister, hurry up and come get it!');
INSERT INTO "notif_data" VALUES(100401,4,'We''ve got tons of EXP potions at the guildhouse! I might just end up bigger than you with these!');
INSERT INTO "notif_data" VALUES(100401,5,'There’s a ton of Mana sitting at the guildhouse! You know, I could really use some new prank supplies...');
INSERT INTO "notif_data" VALUES(100401,6,'The guildhouse is packed to the rafters with items! If you don''t come get ''em quick, don''t blame me if they disappear! ♪');
INSERT INTO "notif_data" VALUES(100601,1,'Hey, big guy, I see your stamina is full again. I was hoping we could go another round or two... ♪');
INSERT INTO "notif_data" VALUES(100601,2,'Your skip tickets at the guildhouse are all full. Now you and I can do it even more... Battle with enemies, I mean! ♪');
INSERT INTO "notif_data" VALUES(100601,3,'Your stamina at the guildhouse is replenished. Hurry back—I don''t think I can wait much longer... ♪');
INSERT INTO "notif_data" VALUES(100601,4,'Oh hey, the guildhouse is full on EXP potions. Don''t you worry—I''m going to keep getting bigger and bigger! ♪');
INSERT INTO "notif_data" VALUES(100601,5,'There''s sooo much Mana at the guildhouse. Ooh, I want it so bad, I can barely control myself...');
INSERT INTO "notif_data" VALUES(100601,6,'Is that a guildhouse full of items you have there, or are you just happy to see me? ♪');
INSERT INTO "notif_data" VALUES(100701,1,'Your stamina is super full! Hurry up! Go buy Miyako pudding!');
INSERT INTO "notif_data" VALUES(100701,2,'Hey you! Full skip tickets at the guildhouse! Time to take Miyako on a pudding hunt!');
INSERT INTO "notif_data" VALUES(100701,3,'All your staminas at the guildhouse are full up! Use them all to get pudding for Miyako!');
INSERT INTO "notif_data" VALUES(100701,4,'Ooo, the guildhouse is full of EXP potions... Pour them on some pudding and give them to Miyako!');
INSERT INTO "notif_data" VALUES(100701,5,'Hey, the guildhouse is super full of Mana! Just what we need for buying all the puddings!');
INSERT INTO "notif_data" VALUES(100701,6,'There''s too many items in the guildhouse now. Come pick them up and give all the puddings to Miyako!');
INSERT INTO "notif_data" VALUES(100801,1,'Oh, look at that—our stamina is full once more. At peak condition, I am the very embodiment of flawless beauty!');
INSERT INTO "notif_data" VALUES(100801,2,'Oh, the guildhouse is full of skip tickets. Spare yourself the battles so you can spend more time basking in my beauty! ♪');
INSERT INTO "notif_data" VALUES(100801,3,'Ah, your stamina at the guildhouse has replenished. Now you can gaze upon my splendor in peak condition! ♪');
INSERT INTO "notif_data" VALUES(100801,4,'I hear there''s full EXP potions at the guildhouse. It would appear my beauty was meant to soar to even greater heights! ♪');
INSERT INTO "notif_data" VALUES(100801,5,'Word is you have Mana to spare at the guildhouse. I wouldn''t be upset if you used it to lavish me with gifts... ♪');
INSERT INTO "notif_data" VALUES(100801,6,'My, you have a lot of items at the guildhouse. I assume they''re all gifts for me?');
INSERT INTO "notif_data" VALUES(100901,1,'Sigurd, our stamina has fully recovered! Now is the time for us to press the attack! Hecate of the Gale shall lay waste to all who would stand in our path!');
INSERT INTO "notif_data" VALUES(100901,2,'skip tickets at our bastion have reached capacity! There''s no need to hesitate. Claim them as your own!');
INSERT INTO "notif_data" VALUES(100901,3,'Our stronghold is overflowing with stamina! Do not squander this precious lifeforce, Sigurd!');
INSERT INTO "notif_data" VALUES(100901,4,'EXP potions have replenished at the guildhouse! I shall obtain greater power, and thus advance on the path to being the mightiest of them all!');
INSERT INTO "notif_data" VALUES(100901,5,'Our guildhouse is brimming with Mana reserves! Sigurd, I trust you will share this wealth with your comrade?');
INSERT INTO "notif_data" VALUES(100901,6,'Your guildhouse is filled to the brim with valuable items! If you don''t claim them, then perhaps I shall!');
INSERT INTO "notif_data" VALUES(101001,1,'Aw look, your stamina is full again. Let''s you and I take a li''l stroll together, my prince. ♪');
INSERT INTO "notif_data" VALUES(101001,2,'The skip tickets at the guildhouse are all full. Hafta love bein'' able to take it easy.');
INSERT INTO "notif_data" VALUES(101001,3,'Gosh, you have full stamina at the guildhouse! What say we go on a li''l patrol together, my prince?');
INSERT INTO "notif_data" VALUES(101001,4,'Gosh, look at all the EXP potions at the guildhouse. Will drinkin'' these make my magic work better?');
INSERT INTO "notif_data" VALUES(101001,5,'Goodness, look at all the Mana at the guildhouse! The way Mana sparkles like jewels is just pretty as can be! ♪');
INSERT INTO "notif_data" VALUES(101001,6,'Your items at the guildhouse are all full, my prince! And you''re just as dandy as ever, too. ♪');
INSERT INTO "notif_data" VALUES(101101,1,'Looks like your stamina is back to full! You know what they say about adventuring—it pays to be well-perspired!');
INSERT INTO "notif_data" VALUES(101101,2,'Hey, you have full skip tickets at the guildhouse! Quick and hasty wins the race, so let''s skirt around those battles!');
INSERT INTO "notif_data" VALUES(101101,3,'Your stamina at the guildhouse is full again! You know what they say—it''s good to save for a snowy day!');
INSERT INTO "notif_data" VALUES(101101,4,'Oh, there''s full EXP potions at the guildhouse! They say the best medicine always tastes like glitter, but... Huh? What does that even mean?');
INSERT INTO "notif_data" VALUES(101101,5,'The guildhouse has full Mana! You know what they say about money—easy come, easy stay!');
INSERT INTO "notif_data" VALUES(101101,6,'You have full items to claim at the guildhouse! If you just let ''em sit there, it''s like casting pearls before twine!');
INSERT INTO "notif_data" VALUES(101201,1,'Ta-daaa! ☆ Your stamina is full! Let''s go help some people!');
INSERT INTO "notif_data" VALUES(101201,2,'Whoa! Piles of skip tickets in the guildhouse! Let''s get a walk in before I take my nap!');
INSERT INTO "notif_data" VALUES(101201,3,'Oho, I can feel it! stamina at the guildhouse... is back to full!');
INSERT INTO "notif_data" VALUES(101201,4,'The guildhouse is brimming with EXP potions! Those can make my superpow—I mean, my m-magic even stronger!');
INSERT INTO "notif_data" VALUES(101201,5,'Yahoo, look at all the Mana in the guildhouse! Surely you can spare some for me, right? Right?');
INSERT INTO "notif_data" VALUES(101201,6,'Zzz... All items... guildhouse... full... Zzz...');
INSERT INTO "notif_data" VALUES(101601,1,'Whoa, look at who''s got full stamina! You''re just buzzing with energy!');
INSERT INTO "notif_data" VALUES(101601,2,'Wow, you have full skip tickets at the guildhouse! You think there''s skip tickets that work on studying, too?');
INSERT INTO "notif_data" VALUES(101601,3,'Hey, you have full stamina at the guildhouse! We''re gonna party today! ☆');
INSERT INTO "notif_data" VALUES(101601,4,'I hear there''s full EXP potions at the guildhouse! Maybe they can help me get better grades?');
INSERT INTO "notif_data" VALUES(101601,5,'You have crazy amounts of Mana at the guildhouse! That means it''s time for the two of us to go shopping!');
INSERT INTO "notif_data" VALUES(101601,6,'Yay, you have full items at the guildhouse! C''mon, let''s go spend ''em all on a big adventure!');
INSERT INTO "notif_data" VALUES(101701,1,'Haitai! Your stamina is full again, so come join me on patrol! ♪');
INSERT INTO "notif_data" VALUES(101701,2,'Heya, the skip tickets are full at the guildhouse! Moving quickly is important in both karate and questing!');
INSERT INTO "notif_data" VALUES(101701,3,'Hey there, your stamina at the guildhouse is full. Let''s use it to dance and sing together!');
INSERT INTO "notif_data" VALUES(101701,4,'Wow, we''ve got full EXP potions at the guildhouse! Drink a few of these, and anyone can become a black belt!');
INSERT INTO "notif_data" VALUES(101701,5,'There''s lots and lots of Mana at the guildhouse. We can spend some of it polishing my karate techniques!');
INSERT INTO "notif_data" VALUES(101701,6,'Heya, all your items at the guildhouse are full! Want me to help you collect them?');
INSERT INTO "notif_data" VALUES(101801,1,'Looks like your stamina is completely refilled. I''ll bet you can handle plenty of extra classwork now... Heehee, let''s give it a shot! ♪');
INSERT INTO "notif_data" VALUES(101801,2,'Oh, you have full skip tickets at the guildhouse! Don''t go thinking those will let you skip your remedial classes, though! ♪');
INSERT INTO "notif_data" VALUES(101801,3,'It seems you have full stamina at the guildhouse. This sounds like a perfect time to start class! ♪');
INSERT INTO "notif_data" VALUES(101801,4,'It appears the guildhouse is full of EXP potions. Looks like we''re both meant to keep growing and growing!');
INSERT INTO "notif_data" VALUES(101801,5,'My, you have a lot of Mana at the guildhouse! Would you like to go shopping together once school is out?');
INSERT INTO "notif_data" VALUES(101801,6,'You have items to claim back at the guildhouse. With these, you''ll be in perfect form to study! ♪');
INSERT INTO "notif_data" VALUES(102001,1,'Eheheh, you''ve got full stamina! ♪ Wanna come play with Mimi, mister?');
INSERT INTO "notif_data" VALUES(102001,2,'Wooow, so many skip tickets at the guildhouse! I wanna go take a walk with you, mister!');
INSERT INTO "notif_data" VALUES(102001,3,'La-la-la-la! ♪ Full stamina at the guildhouse! ♪ Can we hold hands when we go out?');
INSERT INTO "notif_data" VALUES(102001,4,'Your guildhouse is full of these potion thingies! D''you think they could help me grow up fast?');
INSERT INTO "notif_data" VALUES(102001,5,'Wow... What should we do with all this? Oh, hi, mister! Your guildhouse is full of Mana!');
INSERT INTO "notif_data" VALUES(102001,6,'Ooh, look at all these items to get at the guildhouse! Wowie... Can I have some, too?');
INSERT INTO "notif_data" VALUES(102101,1,'U-um, your stamina is back to full... C-can we play a game?');
INSERT INTO "notif_data" VALUES(102101,2,'Um, you have full skip tickets at the guildhouse. I heard they''re really useful.');
INSERT INTO "notif_data" VALUES(102101,3,'Um, you have full stamina at the guildhouse... W-would you like to go on an adventure together?');
INSERT INTO "notif_data" VALUES(102101,4,'There are so many EXP potions at the guildhouse... I wonder if they can help me learn to cook better?');
INSERT INTO "notif_data" VALUES(102101,5,'Um, you have full Mana at the guildhouse... Make sure not to waste it, okay?');
INSERT INTO "notif_data" VALUES(102101,6,'Um, your items at the guildhouse are full. Everybody really likes you, huh? ♪');
INSERT INTO "notif_data" VALUES(102201,1,'All right, your stamina is completely recharged! Now we can do some serious gaming!');
INSERT INTO "notif_data" VALUES(102201,2,'Your skip tickets are full at the guildhouse! Now we''ll be knocking out quests left and right!');
INSERT INTO "notif_data" VALUES(102201,3,'Your stamina at the guildhouse is completely full! Sounds like an opportunity for a nice, long questing session!');
INSERT INTO "notif_data" VALUES(102201,4,'We have a lot of EXP potions at the guildhouse. Leveling up increases stats, too! How cool is that!');
INSERT INTO "notif_data" VALUES(102201,5,'You''ve built up a lot of Mana at the guildhouse. We can use it to buy all kinds of gear that makes completing quests easier!');
INSERT INTO "notif_data" VALUES(102201,6,'You''ve got lots of items at the guildhouse. Come collect them all so we can put them to use on our quests!');
INSERT INTO "notif_data" VALUES(102501,1,'Hello there, you have full stamina again! If you''re going out, perhaps I can join you?');
INSERT INTO "notif_data" VALUES(102501,2,'Oh, you have full skip tickets at the guildhouse. Um, I don''t suppose they would help me finish my work faster, would they?');
INSERT INTO "notif_data" VALUES(102501,3,'You have stamina waiting at the guildhouse. And I''m waiting for you too!');
INSERT INTO "notif_data" VALUES(102501,4,'Oh, your EXP potions at the guildhouse are full. Do you think more experience could cure my klutziness?!');
INSERT INTO "notif_data" VALUES(102501,5,'Wow, look at all the Mana in the guildhouse. If only the Orphanage had that much, imagine all the wonderful things we could do...');
INSERT INTO "notif_data" VALUES(102501,6,'All of your items at the guildhouse are full. Let me get them for—Ack! They slipped right out of my hand!');
INSERT INTO "notif_data" VALUES(102701,1,'Oh, I see that your stamina has fully recovered. Now I can conduct all sorts of tests on you... Teehee. ♪');
INSERT INTO "notif_data" VALUES(102701,2,'The guildhouse is full of skip tickets. Now we can let the fighting take care of itself and spend some quiet time together.');
INSERT INTO "notif_data" VALUES(102701,3,'Oh, your stamina has recovered at the guildhouse. Now that you''re practically bursting with vigor, perhaps I should... Teehee... ♪');
INSERT INTO "notif_data" VALUES(102701,4,'Oh, look at all the EXP potions at the guildhouse. Medicine is a truly wonderful thing... Teehee. ♪');
INSERT INTO "notif_data" VALUES(102701,5,'You have quite a wealth of Mana at the guildhouse. Don''t worry, I''ll decide exactly how you should spend it.');
INSERT INTO "notif_data" VALUES(102701,6,'Your items at the guildhouse are all full. What''s yours is mine... and that includes you. ♪');
INSERT INTO "notif_data" VALUES(102801,1,'Oh, looks like your stamina has recovered. If you''ve got energy to spare, why not lend me a hand?');
INSERT INTO "notif_data" VALUES(102801,2,'You have full skip tickets at the guildhouse. They''re just sitting here gathering dust, so please pick them up quickly, okay?');
INSERT INTO "notif_data" VALUES(102801,3,'You have stamina just sitting at the guildhouse. You shouldn''t neglect your own physical vitality.');
INSERT INTO "notif_data" VALUES(102801,4,'You have full EXP potions at the guildhouse. Experience is vital. It''s an essential part of growth.');
INSERT INTO "notif_data" VALUES(102801,5,'The guildhouse Mana stores are at full capacity. Money and Mana make the world go round, so be sure you spend it prudently.');
INSERT INTO "notif_data" VALUES(102801,6,'You have items to claim at the guildhouse. You know, putting these kinds of things off until later always leads to trouble down the road.');
INSERT INTO "notif_data" VALUES(102901,1,'Now that you have full stamina and all, I was hoping you could come and see me in concert! ♪');
INSERT INTO "notif_data" VALUES(102901,2,'The skip tickets are full at the guildhouse. Do you think they''ll make my lessons more productive?');
INSERT INTO "notif_data" VALUES(102901,3,'Oh, you have full stamina at the guildhouse. I''m always ready to go out on the town, so all you have to do is ask. ♪');
INSERT INTO "notif_data" VALUES(102901,4,'It seems the guildhouse is full of EXP potions. They might even be able to help me become a better idol!');
INSERT INTO "notif_data" VALUES(102901,5,'Your Mana at the guildhouse is full, it seems. Say, would you like to go see a play with me?');
INSERT INTO "notif_data" VALUES(102901,6,'You can''t hold any more items at the guildhouse. Wow, you get almost as many presents as an idol! ♪');
INSERT INTO "notif_data" VALUES(103001,1,'Your stamina is completely restored, Shogun! Now is the time to conquer the lands!');
INSERT INTO "notif_data" VALUES(103001,2,'Shogun! The guildhouse is full of skip tickets. They''re just like using my Ninpo: Flying Squirrel no Jutsu!');
INSERT INTO "notif_data" VALUES(103001,3,'Shogun, your stamina is full at the guildhouse! I bet it works just like my ninja rations!');
INSERT INTO "notif_data" VALUES(103001,4,'The guildhouse is chock full of EXP potions! I can feel the inspiration coming for a new ninja technique!');
INSERT INTO "notif_data" VALUES(103001,5,'The guildhouse is laden with Mana, Shogun! We should save it up to purchase a castle!');
INSERT INTO "notif_data" VALUES(103001,6,'All items at your guildhouse are full, Shogun! They''ll all be vital resources to help us conquer the lands!');
INSERT INTO "notif_data" VALUES(103101,1,'I sense that you are at peak stamina again. Let''s go back out and save more lost souls from their suffering.');
INSERT INTO "notif_data" VALUES(103101,2,'You have full skip tickets at the guildhouse... or at least that''s what the little girl standing right behind you says.');
INSERT INTO "notif_data" VALUES(103101,3,'It appears your stamina is full at the guildhouse. Would you mind assisting me with an exorcism I''ve been asked to perform?');
INSERT INTO "notif_data" VALUES(103101,4,'Guildhouse EXP potions are now full. With these, perhaps I can take another step toward becoming a proper medium.');
INSERT INTO "notif_data" VALUES(103101,5,'A guildhouse full of Mana? Then buy me something, brat! ...S-sorry, that was my father speaking.');
INSERT INTO "notif_data" VALUES(103101,6,'All your items at the guildhouse are full... Or so the spirits tell me.');
INSERT INTO "notif_data" VALUES(103201,1,'Your stamina has fully recovered! Time is money, as they say, so let''s get straight to work!');
INSERT INTO "notif_data" VALUES(103201,2,'You have so many skip tickets at the guildhouse. Why, with these, my horrible sense of direction won''t matter in the slightest!');
INSERT INTO "notif_data" VALUES(103201,3,'My, your stamina is quite full at the guildhouse. Perhaps I can request your services as a knight the next time I have to clear out some monsters.');
INSERT INTO "notif_data" VALUES(103201,4,'Your guildhouse is fully stocked with EXP potions! I''m certain they can help me gain experience as an entrepreneur, too!');
INSERT INTO "notif_data" VALUES(103201,5,'Ah, I see you have a wealth of Mana at the guildhouse. I suppose you could afford a house with that much.');
INSERT INTO "notif_data" VALUES(103201,6,'My, it seems your guildhouse is full of items. Say, don''t you have a butler to handle these things for you?');
INSERT INTO "notif_data" VALUES(103301,1,'Looks like ya got full stamina again. C''mon, hoss, time to roll up those sleeves an'' get to work!');
INSERT INTO "notif_data" VALUES(103301,2,'The guildhouse is chock-full of skip tickets! Ya reckon they can help me practice my stand-up quicker, too?');
INSERT INTO "notif_data" VALUES(103301,3,'Hey, you got a buncha stamina at the guildhouse! Just what we need to keep on truckin'' at the farm!');
INSERT INTO "notif_data" VALUES(103301,4,'You got a gaggle of EXP potions at the guildhouse. I reckon these li''l fellas can help me get ''em all laughing!');
INSERT INTO "notif_data" VALUES(103301,5,'What? You got loads of Mana at the guildhouse? Haven''t ya heard it''s bad "Mana-rs" to leave Mana sittin'' ''round like that?');
INSERT INTO "notif_data" VALUES(103301,6,'Hey, ya got full items waitin'' at the guildhouse. Maybe we can use ''em in some comedy sketches!');
INSERT INTO "notif_data" VALUES(103401,1,'Seeing as you have full stamina and all now... w-would you maybe come and see me?');
INSERT INTO "notif_data" VALUES(103401,2,'You have full skip tickets at the guildhouse. I wonder if they can help shorten my hangovers, too...');
INSERT INTO "notif_data" VALUES(103401,3,'Um, you''ve got full stamina at the guildhouse, so, uh... Do you want to go somewhere, maybe?');
INSERT INTO "notif_data" VALUES(103401,4,'There are lots of EXP potions at the guildhouse. These aren''t going to get me drunk, are they?');
INSERT INTO "notif_data" VALUES(103401,5,'Your Mana is full back at the guildhouse. I say it''s high time for a drink! You''ll be having soft drinks, of course. ♪');
INSERT INTO "notif_data" VALUES(103401,6,'Um, your items at the guildhouse are all full. I-I wish someone would give me gifts, too...');
INSERT INTO "notif_data" VALUES(103801,1,'Our stamina seems to be full again. Maybe we can go checking out bookstores a bit further afield.');
INSERT INTO "notif_data" VALUES(103801,2,'Oh, the skip tickets at the guildhouse are full. Now I can avoid any undue physical exertion in battle.');
INSERT INTO "notif_data" VALUES(103801,3,'It seems you have full stamina at the guildhouse. If I get stronger, maybe I can help everyone, too.');
INSERT INTO "notif_data" VALUES(103801,4,'The EXP potions at the guildhouse are full. I wonder if they can help improve my health, too...');
INSERT INTO "notif_data" VALUES(103801,5,'Oh, we have a lot of Mana at the guildhouse. With this amount, we''ll be able to put plenty of books on our shelves.');
INSERT INTO "notif_data" VALUES(103801,6,'All of the items at the guildhouse are full. Once you finish collecting them, how about we do some reading together?');
INSERT INTO "notif_data" VALUES(104001,1,'Now that we have full stamina again, l-let''s go out to make some friends!');
INSERT INTO "notif_data" VALUES(104001,2,'Um, your skip tickets are full at the guildhouse. I think I might''ve just taken another step toward making friends!');
INSERT INTO "notif_data" VALUES(104001,3,'U-um, you''ve got full stamina at the guildhouse. Can I make more friends if I go on lots of adventures?');
INSERT INTO "notif_data" VALUES(104001,4,'Um, the guildhouse is full of EXP potions. Do you think I can make more friends if I work on my conversation skills?');
INSERT INTO "notif_data" VALUES(104001,5,'Oh, the guildhouse has so much Mana. Maybe giving people Mana is the secret to making friends... Huh? It isn''t?');
INSERT INTO "notif_data" VALUES(104001,6,'Your items at the guildhouse are all full. I-it must be nice to receive so many gifts...');
INSERT INTO "notif_data" VALUES(104201,1,'Our stamina has completely recovered. My songs for the fairies are finished, but I still need to work on some songs for the stage...');
INSERT INTO "notif_data" VALUES(104201,2,'You have full skip tickets at the guildhouse. Please, lend me your strength in keeping the people safe from evil.');
INSERT INTO "notif_data" VALUES(104201,3,'You have maximum stamina at the guildhouse. Would you mind joining me for some singing practice today?');
INSERT INTO "notif_data" VALUES(104201,4,'You’re full up with EXP potions at the guildhouse. Hopefully these will keep my throat in tip-top shape.');
INSERT INTO "notif_data" VALUES(104201,5,'There is full Mana waiting at the guildhouse. It''d be lovely to acquire some new equipment and supplies in addition to the usual songs and skills.');
INSERT INTO "notif_data" VALUES(104201,6,'All of the items at the guildhouse are full. Would you have preferred me to tell you with a song instead?');
INSERT INTO "notif_data" VALUES(104301,1,'Your stamina is back at full. C''mon, we''re heading out!');
INSERT INTO "notif_data" VALUES(104301,2,'I hear your skip tickets are full at the guildhouse. That''ll make our explorations easier for sure.');
INSERT INTO "notif_data" VALUES(104301,3,'I hear ya got full stamina back at the guildhouse. If you''re itchin'' for something to do, let''s go rough up some baddies!');
INSERT INTO "notif_data" VALUES(104301,4,'There are full EXP potions at the guildhouse. Is that your way of saying you want to see me become even stronger?');
INSERT INTO "notif_data" VALUES(104301,5,'You sure do have a lot of Mana at the guildhouse. Doesn''t it make you want to just go blow it all in one big spree?');
INSERT INTO "notif_data" VALUES(104301,6,'Hear you got full items waiting at the guildhouse. Some of them could come in handy in a fight.');
INSERT INTO "notif_data" VALUES(104501,1,'Ahhh, you''re practically bursting with stamina... "His body throbbing with forceful vigor, Mr. Sadist grabbed hold of Kuka and..." Gueheheh...');
INSERT INTO "notif_data" VALUES(104501,2,'Oh my, the guildhouse has so many skip tickets... What are you going to do with me with all that extra time?');
INSERT INTO "notif_data" VALUES(104501,3,'The stamina at the guildhouse is full, but you''re still not coming to take it...? Ahhh... You''re trying to drive me crazy with anticipation, aren''t you?!');
INSERT INTO "notif_data" VALUES(104501,4,'There are full EXP potions at the guildhouse. With these, I can climb that next step on the path of adulthood... Gueheheh...');
INSERT INTO "notif_data" VALUES(104501,5,'You have so much Mana sitting at the guildhouse... Wait! C-could it be that you''re planning on buying me with it?!');
INSERT INTO "notif_data" VALUES(104501,6,'The guildhouse is completely full of items. Just think of all the sick things you could do to me with them... *drool*');
INSERT INTO "notif_data" VALUES(104601,1,'Looks like your stamina is feline good. Time is money! Hurry back so we can claw in every last rupie possible!');
INSERT INTO "notif_data" VALUES(104601,2,'Ya got full skip tickets back at the guildhouse. We''ll be rakin'' in the loot paw over claw with those!');
INSERT INTO "notif_data" VALUES(104601,3,'Seems the guildhouse is at full stamina again. Nyow we can go clobber creeps until we''re a couple of fat cats!');
INSERT INTO "notif_data" VALUES(104601,4,'The guildhouse is littered with EXP potions! This little kitty is still growin'', so these''ll be a big help!');
INSERT INTO "notif_data" VALUES(104601,5,'The guildhouse is overflowing with Mana nyow. We gotta sharpen our claws so we can keep scratching up even more loot!');
INSERT INTO "notif_data" VALUES(104601,6,'Myahoo, you''ve got full items at the guildhouse! Come and get your paws on ''em before they go to waste!');
INSERT INTO "notif_data" VALUES(104701,1,'Ah, your stamina has recovered. The time may be ripe to do battle.');
INSERT INTO "notif_data" VALUES(104701,2,'Your guildhouse''s skip ticket supply is full. Perhaps they could be put to use in carrying out some missions.');
INSERT INTO "notif_data" VALUES(104701,3,'The stamina supply at your guildhouse seems to be full. If you have excess energy, perhaps some training is in order?');
INSERT INTO "notif_data" VALUES(104701,4,'Your EXP potion generator seems full to bursting. Building your strength is the first step to defending justice!');
INSERT INTO "notif_data" VALUES(104701,5,'Your guildhouse is practically overflowing with Mana. While awaiting your return, I was mistaken for a statue...');
INSERT INTO "notif_data" VALUES(104701,6,'All the supplies in your guildhouse have reached maximum capacity. I will watch over them until your return.');
INSERT INTO "notif_data" VALUES(104801,1,'I hear your stamina is back to full. Come on, let''s get out there and make some money!');
INSERT INTO "notif_data" VALUES(104801,2,'The skip tickets are full back at the guildhouse. Make sure you spend them wisely!');
INSERT INTO "notif_data" VALUES(104801,3,'Looks like your stamina is full at the guildhouse. Go and snag it quickly so we can start putting it to good use!');
INSERT INTO "notif_data" VALUES(104801,4,'The EXP potions at the guildhouse are full. More levels means greater efficiency!');
INSERT INTO "notif_data" VALUES(104801,5,'Your Mana is full back at the guildhouse. Let''s spend it on an efficient adventure!');
INSERT INTO "notif_data" VALUES(104801,6,'All of your items at the guildhouse are full. Let''s use them to make our adventures more efficient!');
INSERT INTO "notif_data" VALUES(104901,1,'Uh-oh, look who has full stamina again! How about we go on a picnic... or rather, a big adventure!');
INSERT INTO "notif_data" VALUES(104901,2,'You''ve got full skip tickets at the guildhouse! Now you don''t have to fight any of those scary battles!');
INSERT INTO "notif_data" VALUES(104901,3,'Yoo-hoo, there''s full stamina at the guildhouse! Time to go on an adventure with your big sis!');
INSERT INTO "notif_data" VALUES(104901,4,'You have lots of EXP potions at the guildhouse! I can''t wait to see my little bro all grown up!');
INSERT INTO "notif_data" VALUES(104901,5,'You have lots and lots of Mana at the guildhouse. But don''t worry... Big Sis will be right there to make sure you don''t spend it frivolously! ♪');
INSERT INTO "notif_data" VALUES(104901,6,'The guildhouse is completely full of items! And they''re all yours, just like your big sis!');
INSERT INTO "notif_data" VALUES(105001,1,'Your stamina is back to full! Now, escort me around town as a proper gentleman should!');
INSERT INTO "notif_data" VALUES(105001,2,'You have full skip tickets at the guildhouse. You''ll be using them to take me someplace nice, right?');
INSERT INTO "notif_data" VALUES(105001,3,'Look! stamina at the guildhouse is totally full! Only someone as mature and responsible as me would have noticed.');
INSERT INTO "notif_data" VALUES(105001,4,'There''s lots of EXP potions at the guildhouse! What''s going to happen to me if I keep growing?');
INSERT INTO "notif_data" VALUES(105001,5,'Look at all that Mana you have at the guildhouse! Now''s your chance to take me out to a stylish cafe!');
INSERT INTO "notif_data" VALUES(105001,6,'Hey, your items are all full at the guildhouse! I bet you''d never remember to get them if I didn''t say anything, huh? What a goof!');
INSERT INTO "notif_data" VALUES(105101,1,'My, looks like you have full stamina. If you''re feeling so full of vim and vigor, why not join me for a few experiments?');
INSERT INTO "notif_data" VALUES(105101,2,'The skip tickets at the guildhouse are full. I don''t want to repeat anything that I don''t have to, so let''s put them to good use.');
INSERT INTO "notif_data" VALUES(105101,3,'The stamina back at the guildhouse is full. That''s odd, here I was thinking that lately I haven''t felt as strong as I used to be... Oh, pretend you didn''t hear any of that! ♪');
INSERT INTO "notif_data" VALUES(105101,4,'How nice. Full EXP potions at the guildhouse. You know, any kind of experience can fuel growth.');
INSERT INTO "notif_data" VALUES(105101,5,'Hey, there''s lots of Mana back at the guildhouse. Naturally, you''re going to give it all to me, right?');
INSERT INTO "notif_data" VALUES(105101,6,'All of your items at the guildhouse are full... You know, I''m beginning to think you like to keep me waiting.');
INSERT INTO "notif_data" VALUES(105201,1,'Oh my, your stamina has fully recovered! Let''s go put in some work together! ♪');
INSERT INTO "notif_data" VALUES(105201,2,'Your skip tickets are full at the guildhouse! I hear they make work as easy as pie!');
INSERT INTO "notif_data" VALUES(105201,3,'Uh-oh, you''ve got full stamina at the guildhouse. Eheheh, now we can really chew the cud. ♪');
INSERT INTO "notif_data" VALUES(105201,4,'Looks like the guildhouse is full of EXP potions. Could these be what I need to become a human?');
INSERT INTO "notif_data" VALUES(105201,5,'My, there''s a lot of Mana at the guildhouse! I just love the way it all sparkles!');
INSERT INTO "notif_data" VALUES(105201,6,'Hey, you have full items at the Guildhouse! Must be nice being popular! ♪');
INSERT INTO "notif_data" VALUES(105301,1,'You are back at full stamina once more. But this is no time for sitting idle. Come, adventure awaits us!');
INSERT INTO "notif_data" VALUES(105301,2,'You''ve got a guildhouse full of skip tickets! Streamlining our outings will only make us stronger!');
INSERT INTO "notif_data" VALUES(105301,3,'You have full stamina at the guildhouse! On your feet, soldier! We''re going to run some drills!');
INSERT INTO "notif_data" VALUES(105301,4,'The guildhouse is fully stocked with EXP potions! P-perhaps they can help me grow a little taller, too...');
INSERT INTO "notif_data" VALUES(105301,5,'The guildhouse is overflowing with Mana. You may as well take it. After all, you need it to do pretty much anything, right?');
INSERT INTO "notif_data" VALUES(105301,6,'All items at the guildhouse are fully stocked. It appears you have some very useful supplies in there.');
INSERT INTO "notif_data" VALUES(105701,1,'Your stamina is maxed out again! We''re going to need to work together if we want to become top-class skyfarers!');
INSERT INTO "notif_data" VALUES(105701,2,'You have full skip tickets at the guildhouse! Do you think traveling would be easier, too, if we could fly?');
INSERT INTO "notif_data" VALUES(105701,3,'stamina is back to full at the guildhouse! I feel like no job is too big for us now!');
INSERT INTO "notif_data" VALUES(105701,4,'The EXP potions at the guildhouse are at capacity! I''m going to get stronger and become a great skyfarer just like my father!');
INSERT INTO "notif_data" VALUES(105701,5,'Your Mana has filled up again at the guildhouse! Do you think we''ll be able to afford an airship if we keep saving up?');
INSERT INTO "notif_data" VALUES(105701,6,'The items at the guildhouse are at max capacity! You''ve got all sorts of good stuff there, so don''t let any of it go to waste!');
INSERT INTO "notif_data" VALUES(105801,1,'Your stamina is completely full! But my stomach is completely empty. Let''s go eat!');
INSERT INTO "notif_data" VALUES(105801,2,'You have tons of skip tickets at the guildhouse. These tickets are just like food—you don''t want to let any of them go to waste!');
INSERT INTO "notif_data" VALUES(105801,3,'Both me and the guildhouse have stamina to spare!');
INSERT INTO "notif_data" VALUES(105801,4,'You''ve got tons of EXP potions at the guildhouse! C''mon, let''s go gulp ''em down!');
INSERT INTO "notif_data" VALUES(105801,5,'Oh, you''ve got Mana wasting at the guildhouse! Hey, do you think Mana is edible?');
INSERT INTO "notif_data" VALUES(105801,6,'Every item at the guildhouse is fully stocked! You think there''s any food in there?');
INSERT INTO "notif_data" VALUES(105901,1,'I see that your stamina has fully recovered. I shall accompany you wherever it is you decide to go, my lord.');
INSERT INTO "notif_data" VALUES(105901,2,'Your skip tickets at the guildhouse are full. Would you consider taking some with you on your next adventure?');
INSERT INTO "notif_data" VALUES(105901,3,'Excuse me, your stamina is full at the guildhouse. Hehe, you are so spirited, my lord.');
INSERT INTO "notif_data" VALUES(105901,4,'The EXP potions at the guildhouse are full. I must become stronger so that I can keep my lord safe!');
INSERT INTO "notif_data" VALUES(105901,5,'The guildhouse is full on Mana. I suppose I shouldn''t be surprised that my lord is so skilled at earning it... ♪');
INSERT INTO "notif_data" VALUES(105901,6,'All of your items at the guildhouse are full. These are the fruits of all your hard work, my lord.');
INSERT INTO "notif_data" VALUES(106001,1,'Your stamina is topped off again. So? What''re you sitting there for? We need to get out there and do some quests!');
INSERT INTO "notif_data" VALUES(106001,2,'The skip tickets back at the guildhouse are full. Make sure to grab them if you''re heading out.');
INSERT INTO "notif_data" VALUES(106001,3,'Well, your stamina at the guildhouse is full, so it''s time to get out into the field. C''mon, follow me!');
INSERT INTO "notif_data" VALUES(106001,4,'The guildhouse is all filled up with EXP potions. I''m going to be more powerful than ever before! ♪');
INSERT INTO "notif_data" VALUES(106001,5,'You''ve got full Mana sitting at the guildhouse. It comes in handy pretty much everywhere, so what''s the harm in carrying it with you?');
INSERT INTO "notif_data" VALUES(106001,6,'Hey, you''ve got items sitting at the guildhouse. Come grab them so we can get adventuring!');
INSERT INTO "notif_data" VALUES(102601,1,'Looks like your stamina''s all full. Not that I''m gonna do anything about it, though.');
INSERT INTO "notif_data" VALUES(102601,2,'Hey, your skip tickets are full at the guildhouse. So skip along and get me some sweet buns.');
INSERT INTO "notif_data" VALUES(102601,3,'Your stamina at the guildhouse is all full. Think of all the work you can do on my behalf.');
INSERT INTO "notif_data" VALUES(102601,4,'Those EXP potions at the guildhouse are all full. I''m still gonna laze about if you use them on me, though.');
INSERT INTO "notif_data" VALUES(102601,5,'You see all that Mana at the guildhouse? Go collect it so you can buy me some games and high-grade sweet buns.');
INSERT INTO "notif_data" VALUES(102601,6,'All your items at the guildhouse are full. Phew... Notifications sure are exhausting.');
INSERT INTO "notif_data" VALUES(106301,1,'Your stamina''s all full! Time to go search for Losaria!');
INSERT INTO "notif_data" VALUES(106301,2,'Your skip tickets at the guildhouse are full! It''d be nice if you showed me more places outside the city.');
INSERT INTO "notif_data" VALUES(106301,3,'Your stamina at the guildhouse is all full! Come help me train for my forest guardian trial!');
INSERT INTO "notif_data" VALUES(106301,4,'Look at all those EXP potions at the guildhouse! Maybe they''ll help me become a full-fledged forest guardian?');
INSERT INTO "notif_data" VALUES(106301,5,'Your Mana at the guildhouse is full! I''m almost out of arrows, so that''s perfect!');
INSERT INTO "notif_data" VALUES(106301,6,'All your items at the guildhouse are full! They''re gonna go to waste if you leave them there!');
COMMIT;