BEGIN TRANSACTION;
CREATE TABLE 'room_item_detail' ('room_item_id' INTEGER NOT NULL, 'level' INTEGER NOT NULL, 'item_detail' TEXT NOT NULL, 'lvup_trigger_type' INTEGER NOT NULL, 'lvup_trigger_id' INTEGER NOT NULL, 'lvup_trigger_value' INTEGER NOT NULL, 'lvup_trigger_type_2' INTEGER NOT NULL, 'lvup_trigger_id_2' INTEGER NOT NULL, 'lvup_trigger_value_2' INTEGER NOT NULL, 'lvup_item1_type' INTEGER NOT NULL, 'lvup_item1_id' INTEGER NOT NULL, 'lvup_item1_num' INTEGER NOT NULL, 'lvup_time' INTEGER NOT NULL, PRIMARY KEY('room_item_id','level'));
INSERT INTO "room_item_detail" VALUES(1,1,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,10,0,0,0,1,0,1000,5);
INSERT INTO "room_item_detail" VALUES(1,2,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,20,0,0,0,1,0,2000,30);
INSERT INTO "room_item_detail" VALUES(1,3,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,30,0,0,0,1,0,3000,60);
INSERT INTO "room_item_detail" VALUES(1,4,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,40,0,0,0,1,0,9000,180);
INSERT INTO "room_item_detail" VALUES(1,5,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,50,0,0,0,1,0,15000,300);
INSERT INTO "room_item_detail" VALUES(1,6,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,60,0,0,0,1,0,17000,420);
INSERT INTO "room_item_detail" VALUES(1,7,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,70,0,0,0,1,0,19000,600);
INSERT INTO "room_item_detail" VALUES(1,8,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,75,0,0,0,1,0,20000,720);
INSERT INTO "room_item_detail" VALUES(1,9,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,80,0,0,0,1,0,25000,900);
INSERT INTO "room_item_detail" VALUES(1,10,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,90,0,0,0,1,0,50000,900);
INSERT INTO "room_item_detail" VALUES(1,11,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,100,0,0,0,1,0,55000,900);
INSERT INTO "room_item_detail" VALUES(1,12,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,120,0,0,0,1,0,60000,900);
INSERT INTO "room_item_detail" VALUES(1,13,'This is the desk where Karin, the caretaker of the guildhouse, works. This is where she handles all of the paperwork, such as issuing skip tickets.',101,0,0,0,0,0,1,0,0,0);
INSERT INTO "room_item_detail" VALUES(3,1,'A Landosol scenery. Reminds you of coming back home.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(4,1,'Guildhouse wall paper. The sunshine through the window radiates the room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(5,1,'A transparent wall. You can''t see it, but it protects you from the wind and rain. The outside can be seen from the inside, but the inside cannot be seen from the outside.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(6,1,'Transparent floorboards. You can''t see it, but the floor is there. It would be scary if these floorboards were on a high floor.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(7,1,'Never run out of rice balls. The perfect amount of salt, the right shape, and the fact that you can eat an endless amount makes this a must for foodies!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(8,1,'A book stand where you can place your book of magic. Its fantastic design will make you feel like a great wizard!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(9,1,'Add your favorite vegetables and other ingredients, simmer slowly, and tada!... you have a delicious stew!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(10,1,'A cute costume modeled after Lima and softer than anything else around.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(11,1,'Spreads aromatic oils around the room. It does not use fire, so it is safe to use. The latest trend is a floral scent made with flowers from the Prano Plains.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(12,1,'Spreads aromatic oils around the room. Place it higher up to spread the aroma even wider!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(13,1,'This bookcase can accommodate books of varying sizes, from comics to magic books.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(14,1,'A beautiful white royal bookcase that is especially popular with ladies because of its design and the many books it can hold.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(15,1,'An easy-to-use square table. Can comfortably seat 4 people. Perfect for chatting or even playing cards.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(16,1,'A very practical wooden desk. You can play games, or just talk about love. But there is nothing better than eating on it!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(17,1,'A simple wooden chair. Simple, yet strong. If it does break, you can fix it right away...but only if there is someone who can fix it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(18,1,'This round chair is great for sitting down on. You can''t spin around while seated, but you can talk to someone in any direction.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(20,1,'The wooden fragrance and comfort of this white wooden bed means a good night''s sleep is guaranteed. However, don''t jump up and down on the bed as it might break.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(21,1,'A rustic wooden chest of drawers to store your clothes or any secret savings. It''s bad manners to open it without permission.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(22,1,'Wooden partitions to create a warm and private space.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(23,1,'These walls brighten up a room while the gentle, wooden scent has a relaxing effect on the mind and body.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(24,1,'Wooden floor made of two different colors, waxed and polished for a super smooth surface. It goes well with classroom-like interiors.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(25,1,'A wooden spiral staircase. Don''t be surprised by the creaking steps when you climb up.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(26,1,'A wooden spiral staircase. The kind that makes you want to run down. Just don''t rush down and fall over.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(27,1,'This dark brown cat-legged table is the height of luxury. Place a tablecloth on top for a very elegant look.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(28,1,'A fine, chic mahogany desk from a long-established famous brandthat has become popular with people of all ages.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(29,1,'A dark brown chair with decorative carvings on the back and made from Astraean mahogany, popular for its beautiful appearance and easy modification.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(30,1,'A small but sturdy round chair. It is handy as a step, but dangerous to use for anything other than sitting.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(32,1,'A mahogany wood bed. Place cushions on the headboard and rest your back on it to make a great couch.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(33,1,'A four-drawer chest. It is much deeper than it appears, so you can easily store larger items like wizard''s robes and sticks.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(34,1,'This partition is created from a single piece of mahogany. It is the first piece of furniture that people will see when coming through the front door.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(35,1,'Wallpaper with a mahogany frame for decoration and reinforcement. It is simple, but also brings out the warmth of wood.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(36,1,'A mosaic patterned floorboard in different colors. Remember to wax it and try not to skate on it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(37,1,'Mahogany spiral staircase that takes you to the upper level. The curves of the railing are perfect for sliding on.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(38,1,'A mahogany spiral staircase that takes you to the lower level. Don''t fall down as nobody may notice.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(39,1,'A lovely pink table. It''s good to perhaps write a letter to a loved one.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(40,1,'A large, lovely pink desk, perfectly designed to place sweets and tea sets on. This is ideal for making a lovely room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(41,1,'A cute pink chair. Despite its cute appearance, it is sturdy and easy to sit on.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(42,1,'Upholstered stool with pink and white stripes. Buy enough for everyone, as there could be a fight to sit on them.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(43,1,'A soft pink couch. The pink is the color of the coral found along the Marjan coast and is a very popular color at Landosol.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(44,1,'A comfy couch for two. You can enjoy sitting on it, or fall asleep while lounging on it...',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(45,1,'A pipe bed with a pink frame and pillows. The pillows and blankets come in a variety of colors. Fun dreams are sure to come!♪',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(46,1,'Pink chest of drawers. White wood painted with pink paint. It''s perfect for making things tidy.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(47,1,'A pink plywood partition. Makes things a bit more secluded. It''s proper etiquette in Landosol to pretend not to hear anything you heard.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(48,1,'This pink rug mat is a great addition to any floor. Stand on it to look even cuter.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(49,1,'This pink-walled room makes you want to put flowers and stuffed animals in it. It has attracted the attention of the Landosol Society.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(50,1,'Pink floorboards are the final touch for people who have walls and furniture in pink. Get total color coordination in the traditional happy color of Landosol!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(51,1,'A simple white table that is easy to use. It brings a sense of calmness in any busy room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(52,1,'A large white desk. Its simple yet somehow luxurious design is a favorite of people who want to keep their rooms stylish.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(53,1,'A simple white chair. When paired with a desk, it can create a nice space that looks like the living room of a mansion.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(54,1,'An authentic leather stool. It''s all white and taut now, but as it ages, it becomes softer and better.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(55,1,'People love the firm, natural texture of this rawhide couch. Makes for a practical interior design.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(56,1,'A two-seater rawhide couch. An excellent piece of furniture that can be placed anywhere. But be careful not to spill anything on it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(57,1,'A basic white pipe bed. If you don''t choose the bedding, it will look like one found in a hospital.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(58,1,'A medium-sized pure white chest with drawers. It does not dominate the room, but can remain a mainstay of the interior.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(59,1,'White partitions. Something to put in place to prevent showing the inside of your house directly to guests who enter through the front door.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(60,1,'A half-size rug. Since it''s white, it can go with any color floor. It''s also infused with magic so it doesn''t get dirty, meaning it''s safe for your bare feet.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(61,1,'A wall in constant danger of being graffitied. For that reason, you should keep on hand a supply of poisonous mushrooms from the Elven Forest as they function as a powerful cleaning agent.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(62,1,'Pure white floorboards. You may want to keep it clean by not stepping on them, but that''s what a floor is, so put your feet on them.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(63,1,'A white spiral staircase. The must-do thing in Landosol is to dress up in your favorite clothes, a bouquet of flowers in your hands, and sing your way down.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(64,1,'White stairs that take you down to the lower floor. No gaps between the steps means nothing can fall through.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(65,1,'This table is made of a black wood called Astraea ebony from the southern part of the continent. Even if your interior is a little lacking in style, this table will give it a nice, cool look.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(66,1,'A large black desk. A modern design made from Astraean ebony, it is a favorite of the city''s gentlemen.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(67,1,'A simple black chair. Stylish on its own, but also looks great when combined with white furniture to create a monochrome interior.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(68,1,'A leather stool. There are different grades of leather. Some of them are bogus products made with monster leather that has been dyed, but this the genuine kind.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(69,1,'A black leather couch. Just sitting on it makes you look more sophisticated.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(70,1,'Black leather couch for two. It''s easy to clean and does not stand out. It''s effective in hiding the stains left by children.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(71,1,'A black pipe bed. The chic color and design of the bed goes with any wallpaper and floor. Comes with monotone bedding.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(72,1,'A black accessory case. It''s simple, but the bottom two parts have locks. It''s perfect for storing important things or things you don''t want people to see.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(73,1,'An all-black partition. You may be tempted to look beyond that, but you must not.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(74,1,'A chic, well-designed black half-size rug mat. Highly satisfying, but be careful when washing it, or the color may fade.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(75,1,'Black wallpaper to make your room cool. You cannot go wrong with black, but it does require a good sense of style. Great for advanced interior designers.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(76,1,'Surprisingly, foot prints stick to these floorboards more than any other. Frequent wiping is necessary to maintain their sleekness.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(77,1,'A black spiral staircase. It''s very difficult to see where the steps are, so bring some light with you.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(78,1,'A black spiral staircase that takes you down to the lower floor. It''s black color makes it feel like you are being led into an underground world, or even Hell.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(79,1,'A luxurious, bright red single seat couch with all silk upholstery. Only the Wistaria family has one in Landosol for now.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(80,1,'A two-seater luxury couch. It is paired with the single seat couch. It is really good to lie down all for yourself.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(81,1,'This luxurious rug mat has a red background with gold thread stitching. It''s a good place to leave things you don''t want to forget.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(82,1,'This carpet is made of a combination of yarns of different shades of color and woven into a traditional in Astrum pattern.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(83,1,'A spiral staircase upholstered in red cloth. At first glance, it looks like it could be found in a royal palace, but its much more affordable.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(84,1,'このきらびやかな階段を下りる少女たちの姿はまさに、舞踏会へと向かうお姫様のように映るだろう。　',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(85,1,'These retro-inspired barrels can create a cool and stylish space like a fashionable coffee shop.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(86,1,'A chic brown couch from an long-established famous brand. The scent of leather and the calm color of this couch is perfect for sophisticated moments.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(87,1,'A chic brown two-seater couch from a long-established famous brand. Lie down with the cushions as pillows and you''ll get as good a night''s sleep as you would in a bed.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(88,1,'A slightly larger houseplant. Get more greenery in your life.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(89,1,'A small houseplant. Great for interior decoration and feng shui.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(90,1,'Beautiful flowers in three colors. These will greatly increase your girl power!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(91,1,'A white ceramic vase that will bring a lot of life to the room. It makes any flower in it look beautiful, but sunflowers are perfect for it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(92,1,'A white fireplace fit for royalty. Be enthralled by its luxurious marble and marvel at the attention to detail in its design.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(93,1,'An old-fashioned brick fireplace. You can imagine Santa Claus coming down through this.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(94,1,'A perfect cupboard for storing things. The bottom sliding door is particularly convenient.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(95,1,'Children should not be allowed near this medicine cabinet. Also never make a strange pill and give it to someone...',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(96,1,'A wooden bottle rack. A wide variety of drinks can be stored here for when you are thirsty.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(97,1,'A chic, old-fashioned table clock. The sound of the second hand reveals the attention to detail of the craftsman behind it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(98,1,'A royal white table clock. The fine design of this clock is based on a famous brand and would look at home in a royal palace.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(99,1,'A fishing rod, loved by ladies, that comes in handy when catching fish. It is very popular at Landosol because it is strong and flexible.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(100,1,'Everyone''s favorite cute stuffed cat. So much so that even dog people''s hearts will melt!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(101,1,'Armor of the Defenders of the Throne. Pieced together from iron plates, it can fend off any attack. It comes alive at night...joke!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(102,1,'A beautiful pure white dress, perfect for balls and parties. Every lady should wear this dress at least once.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(103,1,'A lovely cute pink dress made with ribbons and ruffles by a famous designer and is all the rage among the girls at Landosol.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(104,1,'This maid''s outfit perhaps makes you look like a clumsy maid. A welcome from this maid is sure to make anyone feel like a royalty.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(105,1,'A statue of a beautiful woman. These can usually be found in dating spots in the city. Place one in your room to recreate that feeling.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(106,1,'A statue of a famous wizard. He was so powerful that he left his mark on the history of Astraea and is still considered the standard of wizards to this day.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(107,1,'This wall hanging has several kinds of flowers. It''s a gorgeous piece of work that effortlessly adds a stylish touch to your room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(108,1,'A landscape painting by a famous artist. It brings sophistication to any interior when hung on a wall.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(109,1,'A circular painting called "Tondo." No one knows who the model in the painting is, but no one is all that interested, so it''s left as is.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(110,1,'Iron shield for wall mounting. It seems to be popular for those seeking a chivalrous interior design.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(111,1,'Two swords to mount on a wall. Decorate your house like a knight''s house.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(112,1,'Stylish black handrail. It can also be used as partitioning to give more variety to your interior.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(113,1,'Stylish white railing. Place it around the plants for a beautiful flower bed. Just don''t go jumping over or on it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(114,1,'Turn your room into a church with this stained glass partition.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(115,1,'A magnificent brick partition. Set up a lot of partitions to make your own maze.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(116,1,'A solid wall made of stone. Can hold any enemy back!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(117,1,'Press your cheeks on this marble wall that is cool to the touch on cold days and warm on hot ones.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(118,1,'A brick wall that can withstand rain and wind, but that doesn''t mean you can lay out your frustrations on it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(119,1,'Cobblestone floor. While it is tough, it''s dangerous to play on it, so best to avoid that.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(120,1,'Beautiful furniture is perfect on this marble flooring for a luxurious interior.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(121,1,'This brick flooring can transform your room into something from another world.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(122,1,'A beautifully-designed mosaic tile floor that goes well with a castle-like interior.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(123,1,'Black and white tile flooring that matches the furniture to transform any room!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(124,1,'Red and white tile flooring designed to go with any interior to create a poppy atmosphere.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(125,1,'Cute pink background material. The cute, girly design goes well with lovely furniture.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(126,1,'Pale pink background material. The understated sense of cuteness creates a somewhat more sophisticated atmosphere.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(127,1,'A beautiful blue background material. The blue color is calm and comforting and goes well with plain furniture.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(128,1,'Pale blue background material. This blue color gently wraps around any interior.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(129,1,'Yellow background material. The girls are sure to feel energized like the sun. It goes well with bright interiors.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(130,1,'Pale yellow background material. The warm background, like the sun, will make the girls want to take a nap.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(131,1,'A very realistic tiger rug. Excellent for bare feet and sure to frighten anyone who is near.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(132,1,'White tiles. Can be used alternately with other tiles to create a stylish checkered interior.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(133,1,'Grey tiles to create an austere modern atmosphere. Great for advanced interior designers.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(134,1,'Red tiles in a color that can change the mood of a room in a heartbeat!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(135,1,'Blue tiles. A great choice for people who want to create a cool, tranquil room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(136,1,'Yellow tiles. Their warm and somehow reassuring hue goes great with white furniture! It seems that your design mastery hangs on whether you can incorporate these colors.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(137,1,'Green tiles that are sure to bring color to any room. Combine them with other tiles to make a mosaic pattern.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(138,1,'Purple tiles. Great for anyone who wants a room with a bewitching vibe!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(139,1,'Light brown tiles that go well with both Japanese and Western styles. Perfect for those who want a room with a lived-in feel!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(140,1,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,10,0,0,0,1,0,1000,5);
INSERT INTO "room_item_detail" VALUES(140,2,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,20,0,0,0,1,0,2000,30);
INSERT INTO "room_item_detail" VALUES(140,3,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,30,0,0,0,1,0,3000,60);
INSERT INTO "room_item_detail" VALUES(140,4,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,40,0,0,0,1,0,9000,180);
INSERT INTO "room_item_detail" VALUES(140,5,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,50,0,0,0,1,0,15000,300);
INSERT INTO "room_item_detail" VALUES(140,6,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,60,0,0,0,1,0,17000,420);
INSERT INTO "room_item_detail" VALUES(140,7,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,70,0,0,0,1,0,19000,600);
INSERT INTO "room_item_detail" VALUES(140,8,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,75,0,0,0,1,0,20000,720);
INSERT INTO "room_item_detail" VALUES(140,9,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,80,0,0,0,1,0,25000,900);
INSERT INTO "room_item_detail" VALUES(140,10,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,90,0,0,0,1,0,50000,900);
INSERT INTO "room_item_detail" VALUES(140,11,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,100,0,0,0,1,0,55000,900);
INSERT INTO "room_item_detail" VALUES(140,12,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,120,0,0,0,1,0,60000,900);
INSERT INTO "room_item_detail" VALUES(140,13,'An endless pile of sweets that is something out of a dream. Eat as much as you desire and be happy!',101,0,0,0,0,0,1,0,0,0);
INSERT INTO "room_item_detail" VALUES(141,1,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,10,0,0,0,1,0,1000,5);
INSERT INTO "room_item_detail" VALUES(141,2,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,20,0,0,0,1,0,2000,30);
INSERT INTO "room_item_detail" VALUES(141,3,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,30,0,0,0,1,0,3000,60);
INSERT INTO "room_item_detail" VALUES(141,4,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,40,0,0,0,1,0,9000,180);
INSERT INTO "room_item_detail" VALUES(141,5,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,50,0,0,0,1,0,15000,300);
INSERT INTO "room_item_detail" VALUES(141,6,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,60,0,0,0,1,0,17000,420);
INSERT INTO "room_item_detail" VALUES(141,7,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,70,0,0,0,1,0,19000,600);
INSERT INTO "room_item_detail" VALUES(141,8,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,75,0,0,0,1,0,20000,720);
INSERT INTO "room_item_detail" VALUES(141,9,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,80,0,0,0,1,0,25000,900);
INSERT INTO "room_item_detail" VALUES(141,10,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,90,0,0,0,1,0,50000,900);
INSERT INTO "room_item_detail" VALUES(141,11,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,100,0,0,0,1,0,55000,900);
INSERT INTO "room_item_detail" VALUES(141,12,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,120,0,0,0,1,0,60000,900);
INSERT INTO "room_item_detail" VALUES(141,13,'When water is poured over it, it changes into a magical potion. It has refreshing sweet taste that helps you recover from fatigue. Of course, you can drink it however you feel.',101,0,0,0,0,0,1,0,0,0);
INSERT INTO "room_item_detail" VALUES(142,1,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,10,0,0,0,1,0,1000,5);
INSERT INTO "room_item_detail" VALUES(142,2,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,20,0,0,0,1,0,2000,30);
INSERT INTO "room_item_detail" VALUES(142,3,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,30,0,0,0,1,0,3000,60);
INSERT INTO "room_item_detail" VALUES(142,4,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,40,0,0,0,1,0,9000,180);
INSERT INTO "room_item_detail" VALUES(142,5,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,50,0,0,0,1,0,15000,300);
INSERT INTO "room_item_detail" VALUES(142,6,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,60,0,0,0,1,0,17000,420);
INSERT INTO "room_item_detail" VALUES(142,7,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,70,0,0,0,1,0,19000,600);
INSERT INTO "room_item_detail" VALUES(142,8,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,75,0,0,0,1,0,20000,720);
INSERT INTO "room_item_detail" VALUES(142,9,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,80,0,0,0,1,0,25000,900);
INSERT INTO "room_item_detail" VALUES(142,10,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,90,0,0,0,1,0,50000,900);
INSERT INTO "room_item_detail" VALUES(142,11,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,100,0,0,0,1,0,55000,900);
INSERT INTO "room_item_detail" VALUES(142,12,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,120,0,0,0,1,0,60000,900);
INSERT INTO "room_item_detail" VALUES(142,13,'An egg-shaped container that automatically makes mana. It always emits a beautiful green light. You need to be qualified to use it, but thanks to Karin''s certification, we have been able to set it up.',101,0,0,0,0,0,1,0,0,0);
INSERT INTO "room_item_detail" VALUES(143,1,'A menu board, just like those found in cafes.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(144,1,'Proof that you have conquered the "Cloudtop Peak." Rare, mouthwatering monster meat with the finest marbling that appears only near the summit.',101,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(145,1,'Proof that you have conquered the "Deepwood Oak." It is also known as the "World''s Most Delicious Fruit." Its skin is so hard that it is not easily pierced, but its flesh is exquisite.',101,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(146,1,'Proof that you have conquered the Sheercliff Ruins. A dumpling set made from a recipe obtained from the ruins. A supreme dish made of rare meat and vegetables.',101,0,0,0,0,0,0,0,0,0);
COMMIT;