BEGIN TRANSACTION;
CREATE TABLE 'room_item_detail' ('room_item_id' INTEGER NOT NULL, 'level' INTEGER NOT NULL, 'item_detail' TEXT NOT NULL, 'lvup_trigger_type' INTEGER NOT NULL, 'lvup_trigger_id' INTEGER NOT NULL, 'lvup_trigger_value' INTEGER NOT NULL, 'lvup_trigger_type_2' INTEGER NOT NULL, 'lvup_trigger_id_2' INTEGER NOT NULL, 'lvup_trigger_value_2' INTEGER NOT NULL, 'lvup_item1_type' INTEGER NOT NULL, 'lvup_item1_id' INTEGER NOT NULL, 'lvup_item1_num' INTEGER NOT NULL, 'lvup_time' INTEGER NOT NULL, PRIMARY KEY('room_item_id','level'));
INSERT INTO "room_item_detail" VALUES(1,1,'The desk Karin, caretaker of the guildhouse, uses for work. This is where she handles all of her paperwork and tasks, such as issuing skip tickets.',101,0,10,0,0,0,1,0,1000,5);
INSERT INTO "room_item_detail" VALUES(1,2,'The desk Karin, caretaker of the guildhouse, uses for work. This is where she handles all of her paperwork and tasks, such as issuing skip tickets.',101,0,20,0,0,0,1,0,2000,30);
INSERT INTO "room_item_detail" VALUES(1,3,'The desk Karin, caretaker of the guildhouse, uses for work. This is where she handles all of her paperwork and tasks, such as issuing skip tickets.',101,0,30,0,0,0,1,0,3000,60);
INSERT INTO "room_item_detail" VALUES(1,4,'The desk Karin, caretaker of the guildhouse, uses for work. This is where she handles all of her paperwork and tasks, such as issuing skip tickets.',101,0,40,0,0,0,1,0,9000,180);
INSERT INTO "room_item_detail" VALUES(1,5,'The desk Karin, caretaker of the guildhouse, uses for work. This is where she handles all of her paperwork and tasks, such as issuing skip tickets.',101,0,50,0,0,0,1,0,15000,300);
INSERT INTO "room_item_detail" VALUES(1,6,'The desk Karin, caretaker of the guildhouse, uses for work. This is where she handles all of her paperwork and tasks, such as issuing skip tickets.',101,0,60,0,0,0,1,0,17000,420);
INSERT INTO "room_item_detail" VALUES(1,7,'The desk Karin, caretaker of the guildhouse, uses for work. This is where she handles all of her paperwork and tasks, such as issuing skip tickets.',101,0,70,0,0,0,1,0,19000,600);
INSERT INTO "room_item_detail" VALUES(1,8,'The desk Karin, caretaker of the guildhouse, uses for work. This is where she handles all of her paperwork and tasks, such as issuing skip tickets.',101,0,75,0,0,0,1,0,20000,720);
INSERT INTO "room_item_detail" VALUES(1,9,'The desk Karin, caretaker of the guildhouse, uses for work. This is where she handles all of her paperwork and tasks, such as issuing skip tickets.',101,0,0,0,0,0,1,0,25000,900);
INSERT INTO "room_item_detail" VALUES(3,1,'Landosol scenery reminiscent of home that puts you at ease.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(4,1,'Guildhouse wallpaper. The sunshine filtering through the window gently illuminates the room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(5,1,'A transparent wall. You can''t see it, but it will protect you from the wind and rain. The wall is made so that the outside can be seen from the inside, but the inside cannot be seen from the outside.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(6,1,'Transparent floorboards. You can''t see it, but the floor is there. It might be a little scary to use these floorboards for somewhere high up.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(7,1,'You''ll never run out with this rice ball. The perfect amount of salt, the right shape, and the fact that you can eat it endlessly makes this a must for foodies!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(8,1,'A book stand where you can place your favorite book of magic. Its fantastical design will make you feel like a powerful wizard!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(9,1,'Throw in your favorite vegetables and ingredients, simmer slowly, and ta-da! Delicious stew for dinner tonight!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(10,1,'A cute plush toy modeled after Lima that''s softer than anything else.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(11,1,'Diffuses aromatic oils around the room. It is very safe as it does not use fire. The latest trend is a floral scent made with flowers from the Prano Plains.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(12,1,'Diffuses aromatic oils around the room. Place it higher up for the fragrance to spread even wider!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(13,1,'This bookcase can accommodate books of varying sizes, from comics to magic books.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(14,1,'A gorgeous white bookcase. It''s especially popular with the ladies because of its design and the large number of books it can hold.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(15,1,'A versatile, square table that can easily accommodate four people. Perfect for chatting or playing cards on.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(16,1,'A practical, wooden desk. You can play games on it, or sit and talk about relationships for hours. But in the end, nothing beats having everyone sit around the table for a nice meal!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(17,1,'A simple wooden chair that''s plain but durable. If it happens to break, it can be fixed right away—if there''s someone who can fix it, of course.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(18,1,'This round chair is great for taking a short break. You can''t spin around on it, but you can turn to talk in any direction while seated.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(20,1,'The fragrance and comfort of this white, wooden bed means a good night''s sleep is guaranteed. But don''t jump up and down on the bed as it might break.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(21,1,'A rustic, wooden chest of drawers to store things like clothes or any secret savings. It''s bad manners to open it without permission.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(22,1,'Wooden partitions to create a warm, private space.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(23,1,'These wooden walls brighten up the room as their gentle fragrance relaxes the mind and body.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(24,1,'Wooden floor made of two different shades of wood, waxed and polished for a super smooth surface. This type of flooring suits places like classrooms.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(25,1,'A wooden spiral staircase. The creaking steps when you climb up might remind you of home.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(26,1,'A wooden spiral staircase that makes you want to run down it. Just be careful not to rush and fall over.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(27,1,'This dark brown, cat-legged table is the height of luxury. Place a tablecloth on top for a tasteful and elegant look.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(28,1,'A chic, mahogany desk from a famous, long-established brand with a hint of sophistication catered toward the older generation.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(29,1,'A dark brown chair with decorative carvings on the back. Made from Astraean mahogany, its beautiful appearance and customizability make it a popular item.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(30,1,'A small but sturdy, round chair. It may look handy as a step, but using it for anything other than sitting is dangerous.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(32,1,'A mahogany wooden bed. Place cushions on the headboard and rest your back on it for a great couch.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(33,1,'A four-drawer chest. It is much deeper than it appears, so you can easily store larger items like wizard''s robes and sticks.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(34,1,'A partition created from a single piece of mahogany. Since it will be the first piece of furniture people see when coming in through the front door, this partition was crafted with great care to detail.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(35,1,'Wallpaper with a mahogany frame for decoration and reinforcement. While simple, the wood brings out a sense of warmth.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(36,1,'Mosaic patterned floorboards in different colors. Remember to wax the floor and try not to skate on it after.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(37,1,'A mahogany, spiral staircase that takes you to the upper floor. The curve of the railing makes it perfect for sliding on.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(38,1,'A mahogany, spiral staircase that takes you to the lower floor. Be careful not to fall, as it might take a while for someone to notice.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(39,1,'A charming pink table. It may be just perfect for writing a letter to a loved one.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(40,1,'A lovely pink desk, perfectly designed with enough space for a tea set and an assortment of desserts. It''s the perfect addition to a fancy room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(41,1,'A cute pink chair. Despite its dainty appearance, it is sturdy and easy to sit on.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(42,1,'Upholstered stool with pink and white stripes. Make sure to get enough of these stools for everyone, as there could be a scuffle to sit on one.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(43,1,'A soft pink couch. This pink is a very popular color at Landosol and is the same shade as the coral found along the Marjan coast.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(44,1,'A comfy couch for two. You can relax as you sit on it, or even find yourself falling asleep as you''re lounging.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(45,1,'A pipe bed with a pink frame and pillows. The pillows and blankets come in a variety of shades. Fun dreams are sure to come!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(46,1,'A chest of drawers with white wood painted in pink. It''s perfect for storing everyday items and keeping the room tidy.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(47,1,'A pink plywood partition that helps give a little more privacy, though not soundproof. It''s proper etiquette in Landosol to pretend not to have overheard anything.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(48,1,'This pink rug adds an accent to the room and will make anyone standing on it look even more charming.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(49,1,'This pink-walled room will make anyone want to decorate it with flowers and stuffed animals. This cute-on-cute phenomenon has attracted the attention of the Landosol Academic Society.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(50,1,'Install these pink floorboards with pink walls and furniture to complete the look. Make your room uniform in the traditional, happy color of Landosol!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(51,1,'A simple, white table that''s extremely versatile. It brings a sense of calmness to any busy room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(52,1,'A large white desk. Its simple yet somewhat luxurious design is a favorite among those who want to keep their rooms stylishly tidy.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(53,1,'A simple white chair. Put it together with a desk, and it''ll look like something you might imagine in the living room of a luxurious mansion.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(54,1,'A stool made of genuine leather. It''s all white and taut now, but as it ages, it becomes softer and more comfortable.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(55,1,'People love the firm, natural texture of this ecru couch. Makes for a practical interior design.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(56,1,'This ecru, two-seater couch is an excellent piece of furniture that looks good in any part of the room. Just be careful not to spill anything on it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(57,1,'A basic, white pipe bed that gives a clean look. But choose your bedding carefully, or it might look like a bed at the hospital.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(58,1,'A medium-sized, white drawer. While the color and design don''t necessarily stand out, the subtlety makes this item perfect for serving as the mainstay of the room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(59,1,'White partitions that can be set up to prevent guests from seeing the inside of your house when they enter through the front door.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(60,1,'A white, half-size rug that goes with any color floor. It''s also infused with magic to prevent it from getting dirty, so it''s safe to step on this rug with your shoes or your bare feet.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(61,1,'A wall in constant danger of being graffitied on. You should always keep a supply of poisonous mushrooms from the Elven Forest on hand as they function as powerful cleaning agents.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(62,1,'Pure white floorboards. You may want to avoid stepping on them in hopes of keeping them clean, but stepping is what a floor is for, so don''t be shy.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(63,1,'A white spiral staircase. The thing to do in Landosol right now is to dress up in your favorite clothes and sing your way down the steps with a bouquet of flowers in your hand.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(64,1,'White stairs that take you down to the lower floor. No gaps between the steps means nothing can fall through.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(65,1,'This table is made of a black wood called Astraean ebony from the southern part of the continent. Even if your room is a little lacking in style, this table will give it a nice, cool look.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(66,1,'A large black desk. Made from Astraean ebony, its modern design is popular with the gentlemen in the city.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(67,1,'A simple black chair. Though stylish enough on its own, it also looks great with white furniture for a monochrome interior.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(68,1,'A leather stool. Though there are different grades of leather with some bogus products using dyed monster hide, this stool is made with genuine leather.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(69,1,'A black leather couch. Just sitting on it will make you look like a person of class.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(70,1,'A black, leather couch for two. It''s easy to clean and effective in hiding stains left by children.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(71,1,'A black pipe bed. The chic color and design of the bed go with any wallpaper or flooring. Comes with classy, monotone bedding.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(72,1,'A simple, black accessory case. The bottom two parts have locks, making it perfect for storing important things that you don''t want people to see.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(73,1,'An all-black partition. You may be tempted to look behind it, but you must not under any circumstances.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(74,1,'This black, half-size rug is chic and well-designed. Handle carefully when washing as the color may fade.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(75,1,'Black wallpaper to give your room that extra touch. Though you can never go wrong with black, it does require a good sense of style to incorporate it. Great for advanced interior designers.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(76,1,'Footprints stick surprisingly well to these floorboards. Frequent wiping is necessary to maintain their sleekness.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(77,1,'A black spiral staircase. It''s very difficult to see where the steps are, so make sure to turn on the light when you use it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(78,1,'A black, spiral staircase that takes you down to the lower floor. Its somber color gives a feeling of being led into a dark, underground world—or even hell.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(79,1,'A luxurious, bright red couch with all-silk upholstery. Currently, only the Wistaria family owns one in all of Landosol.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(80,1,'A two-seater luxury couch that can be put together with a single-seater, making it the perfect place to stretch out for a nap.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(81,1,'This luxurious, red rug with gold stitching can make anything you put on it stand out.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(82,1,'This carpet is made of a combination of yarns. The different shades of color are woven into a traditional Astrum pattern.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(83,1,'A spiral staircase upholstered in red cloth. An affordable item that looks like it could be found in a royal palace at first glance.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(84,1,'Any girl descending this glittering staircase will look like a princess on her way to the ball.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(85,1,'These retro, wooden barrels help create a cool and stylish space like that of a sophisticated coffee shop.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(86,1,'A chic brown couch from a famous, long-established brand. The leather scent and the calm color of this couch are perfect for resting in a refined space.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(87,1,'A chic, brown two-seater couch from a famous, long-established brand. Lie down using the cushions as pillows and you''ll get as good a night''s sleep as you would in a bed.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(88,1,'A slightly larger houseplant. Get more greenery in your life.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(89,1,'A small houseplant. Great for decoration and feng shui.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(90,1,'Beautiful flowers in three different colors that will put you in a sunny mood.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(91,1,'A white ceramic vase that brings life into the room. Any flower looks beautiful in it, but sunflowers suit this vase perfectly.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(92,1,'A white fireplace fit for royalty. The luxurious marble and attention to detail in its design are enthralling.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(93,1,'An old-fashioned brick fireplace. You can almost see Santa Claus coming down through it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(94,1,'A cupboard perfect for storing things with a convenient, sliding door at the bottom.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(95,1,'A medicine cabinet. Children should not be allowed near it. Be sure to handle the medicine carefully and don''t use it to make anything strange for someone.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(96,1,'A wooden bottle rack. A wide variety of drinks can be stored here for when you''re thirsty.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(97,1,'A chic, old-fashioned table clock. The soft sound of the second hand reveals the attention to detail of the craftsman behind it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(98,1,'A lavish, white table clock. The fine design of this clock is based on a distinguished brand and would look at home in a royal palace.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(99,1,'A fishing rod the ladies like to use when catching fish. It is very popular in Landosol because of its durability as well as flexibility.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(100,1,'Everyone''s favorite stuffed cat. It is so adorable that even those who prefer dogs will find their hearts melting!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(101,1,'A suit of armor modeled after that of the Defenders of the Throne. Pieced together from iron plates, it can stand against any attack. It also comes alive at night... Just kidding.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(102,1,'A beautiful white dress that''s perfect for balls and parties. Every girl needs to try this dress on at least once.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(103,1,'This lovely pink dress by a famous designer comes with an abundance of ribbons and ruffles, making it all the rage among the girls in Landosol.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(104,1,'A charming outfit made to resemble that of everyone''s favorite maid. A word of welcome from someone in this outfit is sure to make anyone feel like royalty.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(105,1,'A statue of a beautiful woman that''s often found at popular date spots in the city. Now you can place one in your room to recreate that feeling.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(106,1,'A statue of a famous wizard. He was so powerful that he left his mark on the history of Astraea and is still considered a standard for wizards to this day.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(107,1,'This wall hanging is comprised of several kinds of flowers. It''s a gorgeous piece of work that effortlessly adds a touch of style to your room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(108,1,'A landscape painting by a famous artist. It brings sophistication to any room when hung on a wall.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(109,1,'A round painting titled "Tondo." No one knows who the model in the painting is, but no one is all that interested either, so it''s being left as is.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(110,1,'Iron shield that can be mounted on a wall. It seems to be popular with those seeking a design reminiscent of knights and chivalry.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(111,1,'A pair of swords that can be mounted on a wall. Though the swords aren''t for practical use, they''ll make your house look just like a knight''s.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(112,1,'Stylish black handrail. It can also be used as partitioning to give more variety to your interior.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(113,1,'Stylish white railing. Place it around the plants for a beautiful flower bed. Just don''t go jumping over or on it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(114,1,'Turn your room into a church with this beautiful stained glass partition!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(115,1,'A magnificent brick partition. You can use these partitions to make your own maze in the room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(116,1,'A solid wall made of stone that can hold any enemy back.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(117,1,'Press your cheeks on this cold marble wall to cool yourself down on a hot day.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(118,1,'A brick wall that can withstand wind and rain—but that doesn''t mean you can lay out your frustrations on it.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(119,1,'Cobblestone flooring that''s quite hard. It may be best to avoid running around on it as it could be dangerous.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(120,1,'Marble flooring that goes well with refined furniture for a luxurious interior.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(121,1,'This brick flooring can transform your room into one from a foreign country.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(122,1,'A beautifully designed mosaic tile floor that goes well with castle-like decor.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(123,1,'Black and white tile flooring that matches monochrome furniture to transform any room into a unique space!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(124,1,'This red and white tile flooring is designed to go with any kind of interior and creates a fun atmosphere.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(125,1,'Cute pink background material. The delicate, girly design goes well with elegant furniture.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(126,1,'Pale pink background material. Its subtle charm gives a somewhat sophisticated atmosphere to the room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(127,1,'Beautiful, blue background material. The calm, azure color is comforting and goes well with plain furniture.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(128,1,'Pale blue background material. The azure color gently envelops the room to create a relaxing atmosphere.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(129,1,'Yellow background material. The girls are sure to feel energized like the sun. It goes well with bright interiors.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(130,1,'Pale yellow background material. Just like the sun, the warm background will lull the girls into a comfortable slumber.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(131,1,'A tiger rug that''s excellent for keeping bare feet warm. It''s so realistic that you can almost hear it roar.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(132,1,'White tiles that can be alternated with other tiles to create a stylish, checkered look.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(133,1,'Grey tiles to create an austere yet modern atmosphere. Great for advanced interior designers.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(134,1,'Red tiles. Their vivid color could change the mood of a room in a heartbeat!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(135,1,'Blue tiles. A great choice for those looking to add a cool, tranquil touch to their room.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(136,1,'Yellow tiles. The relaxing, warm hue goes well with white furniture. It''s said that mastering the art of design starts from incorporating this kind of color into your interior.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(137,1,'Green tiles that are sure to bring color to any room. Combine them with other tiles to make a mosaic pattern.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(138,1,'Purple tiles. Great for anyone looking to add a sophisticated and bewitching vibe to their room!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(139,1,'Light brown tiles that go well with both Japanese and Western-style interiors. Perfect for those who want a room with a practical feel!',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(140,1,'An endless mountain of sweets that is something out of a dream. Eat to your heart''s content and be happy!',101,0,10,0,0,0,1,0,1000,5);
INSERT INTO "room_item_detail" VALUES(140,2,'An endless mountain of sweets that is something out of a dream. Eat to your heart''s content and be happy!',101,0,20,0,0,0,1,0,2000,30);
INSERT INTO "room_item_detail" VALUES(140,3,'An endless mountain of sweets that is something out of a dream. Eat to your heart''s content and be happy!',101,0,30,0,0,0,1,0,3000,60);
INSERT INTO "room_item_detail" VALUES(140,4,'An endless mountain of sweets that is something out of a dream. Eat to your heart''s content and be happy!',101,0,40,0,0,0,1,0,9000,180);
INSERT INTO "room_item_detail" VALUES(140,5,'An endless mountain of sweets that is something out of a dream. Eat to your heart''s content and be happy!',101,0,50,0,0,0,1,0,15000,300);
INSERT INTO "room_item_detail" VALUES(140,6,'An endless mountain of sweets that is something out of a dream. Eat to your heart''s content and be happy!',101,0,60,0,0,0,1,0,17000,420);
INSERT INTO "room_item_detail" VALUES(140,7,'An endless mountain of sweets that is something out of a dream. Eat to your heart''s content and be happy!',101,0,70,0,0,0,1,0,19000,600);
INSERT INTO "room_item_detail" VALUES(140,8,'An endless mountain of sweets that is something out of a dream. Eat to your heart''s content and be happy!',101,0,75,0,0,0,1,0,20000,720);
INSERT INTO "room_item_detail" VALUES(140,9,'An endless mountain of sweets that is something out of a dream. Eat to your heart''s content and be happy!',101,0,0,0,0,0,1,0,25000,900);
INSERT INTO "room_item_detail" VALUES(141,1,'When water is poured over it, it changes into a magical potion. Its refreshing, sweet taste helps one recover from fatigue, though it can be enjoyed at any time.',101,0,10,0,0,0,1,0,1000,5);
INSERT INTO "room_item_detail" VALUES(141,2,'When water is poured over it, it changes into a magical potion. Its refreshing, sweet taste helps one recover from fatigue, though it can be enjoyed at any time.',101,0,20,0,0,0,1,0,2000,30);
INSERT INTO "room_item_detail" VALUES(141,3,'When water is poured over it, it changes into a magical potion. Its refreshing, sweet taste helps one recover from fatigue, though it can be enjoyed at any time.',101,0,30,0,0,0,1,0,3000,60);
INSERT INTO "room_item_detail" VALUES(141,4,'When water is poured over it, it changes into a magical potion. Its refreshing, sweet taste helps one recover from fatigue, though it can be enjoyed at any time.',101,0,40,0,0,0,1,0,9000,180);
INSERT INTO "room_item_detail" VALUES(141,5,'When water is poured over it, it changes into a magical potion. Its refreshing, sweet taste helps one recover from fatigue, though it can be enjoyed at any time.',101,0,50,0,0,0,1,0,15000,300);
INSERT INTO "room_item_detail" VALUES(141,6,'When water is poured over it, it changes into a magical potion. Its refreshing, sweet taste helps one recover from fatigue, though it can be enjoyed at any time.',101,0,60,0,0,0,1,0,17000,420);
INSERT INTO "room_item_detail" VALUES(141,7,'When water is poured over it, it changes into a magical potion. Its refreshing, sweet taste helps one recover from fatigue, though it can be enjoyed at any time.',101,0,70,0,0,0,1,0,19000,600);
INSERT INTO "room_item_detail" VALUES(141,8,'When water is poured over it, it changes into a magical potion. Its refreshing, sweet taste helps one recover from fatigue, though it can be enjoyed at any time.',101,0,75,0,0,0,1,0,20000,720);
INSERT INTO "room_item_detail" VALUES(141,9,'When water is poured over it, it changes into a magical potion. Its refreshing, sweet taste helps one recover from fatigue, though it can be enjoyed at any time.',101,0,0,0,0,0,1,0,25000,900);
INSERT INTO "room_item_detail" VALUES(142,1,'An egg-shaped device that automatically makes mana and emits a beautiful, green light. You need to be qualified to use it, but the device can be easily set up thanks to Karin''s certification.',101,0,10,0,0,0,1,0,1000,5);
INSERT INTO "room_item_detail" VALUES(142,2,'An egg-shaped device that automatically makes mana and emits a beautiful, green light. You need to be qualified to use it, but the device can be easily set up thanks to Karin''s certification.',101,0,20,0,0,0,1,0,2000,30);
INSERT INTO "room_item_detail" VALUES(142,3,'An egg-shaped device that automatically makes mana and emits a beautiful, green light. You need to be qualified to use it, but the device can be easily set up thanks to Karin''s certification.',101,0,30,0,0,0,1,0,3000,60);
INSERT INTO "room_item_detail" VALUES(142,4,'An egg-shaped device that automatically makes mana and emits a beautiful, green light. You need to be qualified to use it, but the device can be easily set up thanks to Karin''s certification.',101,0,40,0,0,0,1,0,9000,180);
INSERT INTO "room_item_detail" VALUES(142,5,'An egg-shaped device that automatically makes mana and emits a beautiful, green light. You need to be qualified to use it, but the device can be easily set up thanks to Karin''s certification.',101,0,50,0,0,0,1,0,15000,300);
INSERT INTO "room_item_detail" VALUES(142,6,'An egg-shaped device that automatically makes mana and emits a beautiful, green light. You need to be qualified to use it, but the device can be easily set up thanks to Karin''s certification.',101,0,60,0,0,0,1,0,17000,420);
INSERT INTO "room_item_detail" VALUES(142,7,'An egg-shaped device that automatically makes mana and emits a beautiful, green light. You need to be qualified to use it, but the device can be easily set up thanks to Karin''s certification.',101,0,70,0,0,0,1,0,19000,600);
INSERT INTO "room_item_detail" VALUES(142,8,'An egg-shaped device that automatically makes mana and emits a beautiful, green light. You need to be qualified to use it, but the device can be easily set up thanks to Karin''s certification.',101,0,75,0,0,0,1,0,20000,720);
INSERT INTO "room_item_detail" VALUES(142,9,'An egg-shaped device that automatically makes mana and emits a beautiful, green light. You need to be qualified to use it, but the device can be easily set up thanks to Karin''s certification.',101,0,0,0,0,0,1,0,25000,900);
INSERT INTO "room_item_detail" VALUES(143,1,'A menu board, just like those found in cafes. Desserts of the day are usually written on the blackboard with markers and chalk.',0,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(144,1,'Proof that you have conquered the "Cloudtop Peak." Rare, mouthwatering monster meat with the finest marbling that appears only near the summit.',101,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(145,1,'Proof that you have conquered the "Deepwood Oak." It is also known as the "World''s Most Delicious Fruit." Though the skin is hard and difficult to pierce, the flesh is exquisite.',101,0,0,0,0,0,0,0,0,0);
INSERT INTO "room_item_detail" VALUES(146,1,'Proof that you have conquered the Sheercliff Ruins. A dumpling set made from a recipe obtained from the ruins. A supreme dish made of rare meat and vegetables.',101,0,0,0,0,0,0,0,0,0);
COMMIT;