BEGIN TRANSACTION;
CREATE TABLE 'room_emotion_icon' ('id' INTEGER NOT NULL, 'enable_auto' INTEGER NOT NULL, 'enable_tap' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO "room_emotion_icon" VALUES(0,0,0);
INSERT INTO "room_emotion_icon" VALUES(1,0,0);
INSERT INTO "room_emotion_icon" VALUES(2,0,0);
INSERT INTO "room_emotion_icon" VALUES(3,0,0);
INSERT INTO "room_emotion_icon" VALUES(4,1,1);
INSERT INTO "room_emotion_icon" VALUES(5,1,1);
INSERT INTO "room_emotion_icon" VALUES(6,1,1);
INSERT INTO "room_emotion_icon" VALUES(7,1,1);
INSERT INTO "room_emotion_icon" VALUES(8,1,1);
INSERT INTO "room_emotion_icon" VALUES(9,1,1);
INSERT INTO "room_emotion_icon" VALUES(10,1,1);
INSERT INTO "room_emotion_icon" VALUES(11,0,0);
INSERT INTO "room_emotion_icon" VALUES(12,0,0);
INSERT INTO "room_emotion_icon" VALUES(13,1,1);
INSERT INTO "room_emotion_icon" VALUES(14,0,0);
INSERT INTO "room_emotion_icon" VALUES(15,0,0);
INSERT INTO "room_emotion_icon" VALUES(16,0,0);
INSERT INTO "room_emotion_icon" VALUES(17,0,0);
COMMIT;