BEGIN TRANSACTION;
CREATE TABLE 'room_effect' ('id' INTEGER NOT NULL, 'reward_get' INTEGER NOT NULL, 'jukebox' INTEGER NOT NULL, 'nebbia' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO "room_effect" VALUES(1,1,0,0);
INSERT INTO "room_effect" VALUES(2,2,0,0);
INSERT INTO "room_effect" VALUES(3,3,0,0);
INSERT INTO "room_effect" VALUES(4,4,0,0);
INSERT INTO "room_effect" VALUES(5,5,0,0);
INSERT INTO "room_effect" VALUES(6,6,0,0);
INSERT INTO "room_effect" VALUES(7,7,0,0);
INSERT INTO "room_effect" VALUES(8,8,0,0);
INSERT INTO "room_effect" VALUES(9,0,1,0);
INSERT INTO "room_effect" VALUES(10,0,0,1);
INSERT INTO "room_effect" VALUES(11,11,0,0);
COMMIT;