BEGIN TRANSACTION;
CREATE TABLE 'room_chat_info' ('id' INTEGER NOT NULL, 'formation_id' INTEGER NOT NULL, 'scenario_id' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO "room_chat_info" VALUES(1,2,1);
INSERT INTO "room_chat_info" VALUES(2,1,2);
INSERT INTO "room_chat_info" VALUES(3,3,3);
INSERT INTO "room_chat_info" VALUES(4,2,4);
INSERT INTO "room_chat_info" VALUES(5,2,5);
INSERT INTO "room_chat_info" VALUES(6,2,6);
INSERT INTO "room_chat_info" VALUES(7,2,7);
INSERT INTO "room_chat_info" VALUES(8,2,8);
INSERT INTO "room_chat_info" VALUES(9,2,9);
INSERT INTO "room_chat_info" VALUES(10,2,10);
INSERT INTO "room_chat_info" VALUES(11,2,11);
INSERT INTO "room_chat_info" VALUES(12,2,12);
INSERT INTO "room_chat_info" VALUES(13,1,13);
INSERT INTO "room_chat_info" VALUES(14,1,14);
INSERT INTO "room_chat_info" VALUES(15,1,15);
INSERT INTO "room_chat_info" VALUES(16,1,16);
INSERT INTO "room_chat_info" VALUES(17,1,17);
INSERT INTO "room_chat_info" VALUES(18,1,18);
INSERT INTO "room_chat_info" VALUES(19,2,19);
INSERT INTO "room_chat_info" VALUES(20,4,20);
INSERT INTO "room_chat_info" VALUES(21,2,21);
INSERT INTO "room_chat_info" VALUES(22,2,22);
INSERT INTO "room_chat_info" VALUES(23,5,23);
INSERT INTO "room_chat_info" VALUES(24,5,24);
INSERT INTO "room_chat_info" VALUES(25,5,25);
COMMIT;